//We need to make url exception for windows
// const url = 'src\\assets\\img\\institutions\\'

const url = '/src/assets/img/institutions/'

export const imageData = {
  '21Draw': `${url}21draw-logo.png`,
  Juice: `${url}default-logo.png`,
  'AJ & SMART and JAKE KNAPP': `${url}default-logo.png`,
  'Alive!': `${url}default-logo.png`,
  'Art Challenge': `${url}default-logo.png`,
  'Art-Wod': `${url}artwod-logo.png`,
  ArtOfSteveAhn: `${url}default-logo.png`,
  ArtStation: `${url}artstation-logo.webp`,
  Awwwards: `${url}awwwards-logo.png`,
  'Building a Second Brain': `${url}basb-logo.jpeg`,
  CGCookie: `${url}cgcookie-logo.png`,
  CGMA: `${url}cgma-logo.png`,
  'Character Creation in Blender': `${url}default-logo.png`,
  Cineversity: `${url}cineversity-logo.jpeg`,
  Class101: `${url}class101-logo.png`,
  'Creative Shrimp': `${url}creativeshrimp-logo.png`,
  Domestika: `${url}domestika-logo.png`,
  'Fireship-io': `${url}fireship-logo.png`,
  'Foundation Patreon': `${url}default-logo.png`,
  'Greyscalegorilla Plus': `${url}default-logo.png`,
  Gumroad: `${url}gumroad-logo.png`,
  'Holdframe + School of Motion': `${url}holdframe-logo.png`,
  'James Douglas (moderndayjames)': `${url}default-logo.png`,
  'Learn Squared': `${url}learnsquared-logo.png`,
  Masterclass: `${url}masterclass-logo.png`,
  "Med's Map": `${url}medsmap-logo.webp`,
  'Mograph Mentor': `${url}mo-mentor-logo.png`,
  'Motion Design School': `${url}mds-logo.png`,
  'New Master Academy': `${url}nma-logo.jpeg`,
  Phlearn: `${url}phlearn-logo.png`,
  Pluralsight: `${url}pluralsight-logo.png`,
  'Polygon Runway': `${url}polygon-runway-logo.png`,
  'Project City': `${url}project-city-logo.svg`,
  Proko: `${url}default-logo.png`,
  'Rad How To Class': `${url}project-city-logo.svg`,
  'Ross Draws Bootcamp': `${url}default-logo.png`,
  'School of Motion': `${url}som-logo.png`,
  Schoolism: `${url}schoolism-logo.png`,
  SkillShare: `${url}skillshare-logo.png`,
  'Stylized Station': `${url}default-logo.png`,
  SuperHi: `${url}superhi-logo.png`,
  Test: `${url}default-logo.png`,
  'The Futur': `${url}thefutur-logo.svg`,
  'The Gnomon Workshop': `${url}gnomon-ws-logo.png`,
  Udemy: `${url}udemy-logo.png`,
  'Watts Atelier': `${url}watts-logo.png`,
  Wingfox: `${url}wingfox-logo.png`
}
